name: Wrangler Deploy
on: 
  push:
    branches:
      - "main"  
jobs:
  deploy:
    name: deploy worker
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         npm install 
      - name: Publish
        # https://github.com/cloudflare/wrangler-action
        uses: cloudflare/wrangler-action@1.3.0
        with:
         apiToken: $({secrets.API_TOKEN})
        env:
         CF_ACCOUNT_ID: ${{secrets.CF_ACCOUNT_ID}}
          

